apiVersion: mesh.knative.dev/v1alpha1
kind: BrokerBinding
metadata:
  name: mtbroker
  namespace: knative-eventing
  labels:
    #eventing.knative.dev/release: "v1.2.0"
    app.kubernetes.io/version: "1.2.0"
    #app.kubernetes.io/name: knative-eventing
    helm.sh/chart: {{ include "mt-broker.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  classes:
    - MTChannelBasedBroker
  kmesh:
    apiVersion: mesh.knative.dev/v1alpha1
    kind: KMesh
    name: default
    namespace: knative-mesh
