/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "knative.dev/kmesh/pkg/apis/mesh/v1alpha1"
)

// FakeKMeshes implements KMeshInterface
type FakeKMeshes struct {
	Fake *FakeMeshV1alpha1
	ns   string
}

var kmeshesResource = schema.GroupVersionResource{Group: "mesh.knative.dev", Version: "v1alpha1", Resource: "kmeshes"}

var kmeshesKind = schema.GroupVersionKind{Group: "mesh.knative.dev", Version: "v1alpha1", Kind: "KMesh"}

// Get takes name of the kMesh, and returns the corresponding kMesh object, and an error if there is any.
func (c *FakeKMeshes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KMesh, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kmeshesResource, c.ns, name), &v1alpha1.KMesh{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KMesh), err
}

// List takes label and field selectors, and returns the list of KMeshes that match those selectors.
func (c *FakeKMeshes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KMeshList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kmeshesResource, kmeshesKind, c.ns, opts), &v1alpha1.KMeshList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KMeshList{ListMeta: obj.(*v1alpha1.KMeshList).ListMeta}
	for _, item := range obj.(*v1alpha1.KMeshList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kMeshes.
func (c *FakeKMeshes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kmeshesResource, c.ns, opts))

}

// Create takes the representation of a kMesh and creates it.  Returns the server's representation of the kMesh, and an error, if there is any.
func (c *FakeKMeshes) Create(ctx context.Context, kMesh *v1alpha1.KMesh, opts v1.CreateOptions) (result *v1alpha1.KMesh, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kmeshesResource, c.ns, kMesh), &v1alpha1.KMesh{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KMesh), err
}

// Update takes the representation of a kMesh and updates it. Returns the server's representation of the kMesh, and an error, if there is any.
func (c *FakeKMeshes) Update(ctx context.Context, kMesh *v1alpha1.KMesh, opts v1.UpdateOptions) (result *v1alpha1.KMesh, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kmeshesResource, c.ns, kMesh), &v1alpha1.KMesh{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KMesh), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKMeshes) UpdateStatus(ctx context.Context, kMesh *v1alpha1.KMesh, opts v1.UpdateOptions) (*v1alpha1.KMesh, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kmeshesResource, "status", c.ns, kMesh), &v1alpha1.KMesh{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KMesh), err
}

// Delete takes name of the kMesh and deletes it. Returns an error if one occurs.
func (c *FakeKMeshes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kmeshesResource, c.ns, name), &v1alpha1.KMesh{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKMeshes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kmeshesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KMeshList{})
	return err
}

// Patch applies the patch and returns the patched kMesh.
func (c *FakeKMeshes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KMesh, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kmeshesResource, c.ns, name, pt, data, subresources...), &v1alpha1.KMesh{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KMesh), err
}
