/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "knative.dev/kmesh/pkg/apis/mesh/v1alpha1"
)

// FakeBrokerBindings implements BrokerBindingInterface
type FakeBrokerBindings struct {
	Fake *FakeMeshV1alpha1
	ns   string
}

var brokerbindingsResource = schema.GroupVersionResource{Group: "mesh.knative.dev", Version: "v1alpha1", Resource: "brokerbindings"}

var brokerbindingsKind = schema.GroupVersionKind{Group: "mesh.knative.dev", Version: "v1alpha1", Kind: "BrokerBinding"}

// Get takes name of the brokerBinding, and returns the corresponding brokerBinding object, and an error if there is any.
func (c *FakeBrokerBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BrokerBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(brokerbindingsResource, c.ns, name), &v1alpha1.BrokerBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BrokerBinding), err
}

// List takes label and field selectors, and returns the list of BrokerBindings that match those selectors.
func (c *FakeBrokerBindings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BrokerBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(brokerbindingsResource, brokerbindingsKind, c.ns, opts), &v1alpha1.BrokerBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BrokerBindingList{ListMeta: obj.(*v1alpha1.BrokerBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.BrokerBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested brokerBindings.
func (c *FakeBrokerBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(brokerbindingsResource, c.ns, opts))

}

// Create takes the representation of a brokerBinding and creates it.  Returns the server's representation of the brokerBinding, and an error, if there is any.
func (c *FakeBrokerBindings) Create(ctx context.Context, brokerBinding *v1alpha1.BrokerBinding, opts v1.CreateOptions) (result *v1alpha1.BrokerBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(brokerbindingsResource, c.ns, brokerBinding), &v1alpha1.BrokerBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BrokerBinding), err
}

// Update takes the representation of a brokerBinding and updates it. Returns the server's representation of the brokerBinding, and an error, if there is any.
func (c *FakeBrokerBindings) Update(ctx context.Context, brokerBinding *v1alpha1.BrokerBinding, opts v1.UpdateOptions) (result *v1alpha1.BrokerBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(brokerbindingsResource, c.ns, brokerBinding), &v1alpha1.BrokerBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BrokerBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBrokerBindings) UpdateStatus(ctx context.Context, brokerBinding *v1alpha1.BrokerBinding, opts v1.UpdateOptions) (*v1alpha1.BrokerBinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(brokerbindingsResource, "status", c.ns, brokerBinding), &v1alpha1.BrokerBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BrokerBinding), err
}

// Delete takes name of the brokerBinding and deletes it. Returns an error if one occurs.
func (c *FakeBrokerBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(brokerbindingsResource, c.ns, name), &v1alpha1.BrokerBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBrokerBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(brokerbindingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BrokerBindingList{})
	return err
}

// Patch applies the patch and returns the patched brokerBinding.
func (c *FakeBrokerBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BrokerBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(brokerbindingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.BrokerBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BrokerBinding), err
}
