# Copyright 2019 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-mesh-admin
  labels:
    mesh.knative.dev/release: devel
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      mesh.knative.dev/controller: "true"
rules: [] # Rules are automatically filled in by the controller manager.

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-mesh-core
  labels:
    mesh.knative.dev/release: devel
    mesh.knative.dev/controller: "true"
rules:
  # Allow creating events associated with resources we are controlling.
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]

  # Allow the reconciliation of exactly our validating webhooks.
  # This is needed for us to patch in caBundle information.
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["list", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["get", "update"]
    resourceNames: ["config.webhook.mesh.knative.dev", "validation.webhook.mesh.knative.dev"]

  # Allow the reconciliation of exactly our mutating webhooks.
  # This is needed for us to patch in caBundle information.
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["list", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["get", "update"]
    resourceNames: ["defaulting.webhook.mesh.knative.dev"]

  # Allow the reconciliation of exactly our CRDs.
  # This is needed for us to patch in conversion webhook information.
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "update"]
    resourceNames: ["brokerbindings.mesh.knative.dev", "kmeshes.mesh.knative.dev"]

  # Allow us to reconcile our resources.
  - apiGroups: ["mesh.knative.dev"]
    resources: ["*"]
    verbs: ["get", "list", "update", "watch"]

  # The webhook configured the namespace as the OwnerRef on various cluster-scoped resources,
  # which requires we can Get the system namespace.
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]
    resourceNames: ["knative-mesh"]

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # A separate cluster role for the things actually needed by this
  # controller's contrived examples.
  name: knative-mesh-resources
  labels:
    mesh.knative.dev/release: devel
    mesh.knative.dev/controller: "true"
rules:
  # AddressableService tracks services, so it needs to be able to list
  # and watch those in whatever namespace folks create those CRDs in
  # to do its job.
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]

  # SimpleDeployment creates and manages Pods, so it needs broad
  # permissions on pods
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "update", "delete", "watch"]

  - apiGroups: ["mesh.knative.dev"]
    resources:
      - "brokerbindings"
      - "brokerbindings/status"
      - "kmeshes"
      - "kmeshes/status"
    verbs: ["create", "get", "list", "update", "delete", "watch", "patch"]

  - apiGroups: ["eventing.knative.dev"]
    resources:
      - "brokers"
      - "brokers/status"
      - "triggers"
      - "triggers/status"
    verbs: ["create", "get", "list", "update", "delete", "watch", "patch"]
