/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "knative.dev/kmesh/pkg/apis/mesh/v1alpha1"
	scheme "knative.dev/kmesh/pkg/client/clientset/versioned/scheme"
)

// KMeshesGetter has a method to return a KMeshInterface.
// A group's client should implement this interface.
type KMeshesGetter interface {
	KMeshes(namespace string) KMeshInterface
}

// KMeshInterface has methods to work with KMesh resources.
type KMeshInterface interface {
	Create(ctx context.Context, kMesh *v1alpha1.KMesh, opts v1.CreateOptions) (*v1alpha1.KMesh, error)
	Update(ctx context.Context, kMesh *v1alpha1.KMesh, opts v1.UpdateOptions) (*v1alpha1.KMesh, error)
	UpdateStatus(ctx context.Context, kMesh *v1alpha1.KMesh, opts v1.UpdateOptions) (*v1alpha1.KMesh, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.KMesh, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.KMeshList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KMesh, err error)
	KMeshExpansion
}

// kMeshes implements KMeshInterface
type kMeshes struct {
	client rest.Interface
	ns     string
}

// newKMeshes returns a KMeshes
func newKMeshes(c *MeshV1alpha1Client, namespace string) *kMeshes {
	return &kMeshes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kMesh, and returns the corresponding kMesh object, and an error if there is any.
func (c *kMeshes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KMesh, err error) {
	result = &v1alpha1.KMesh{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kmeshes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KMeshes that match those selectors.
func (c *kMeshes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KMeshList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.KMeshList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kmeshes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kMeshes.
func (c *kMeshes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kmeshes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a kMesh and creates it.  Returns the server's representation of the kMesh, and an error, if there is any.
func (c *kMeshes) Create(ctx context.Context, kMesh *v1alpha1.KMesh, opts v1.CreateOptions) (result *v1alpha1.KMesh, err error) {
	result = &v1alpha1.KMesh{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kmeshes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kMesh).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a kMesh and updates it. Returns the server's representation of the kMesh, and an error, if there is any.
func (c *kMeshes) Update(ctx context.Context, kMesh *v1alpha1.KMesh, opts v1.UpdateOptions) (result *v1alpha1.KMesh, err error) {
	result = &v1alpha1.KMesh{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kmeshes").
		Name(kMesh.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kMesh).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *kMeshes) UpdateStatus(ctx context.Context, kMesh *v1alpha1.KMesh, opts v1.UpdateOptions) (result *v1alpha1.KMesh, err error) {
	result = &v1alpha1.KMesh{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kmeshes").
		Name(kMesh.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kMesh).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the kMesh and deletes it. Returns an error if one occurs.
func (c *kMeshes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kmeshes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kMeshes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kmeshes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched kMesh.
func (c *kMeshes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KMesh, err error) {
	result = &v1alpha1.KMesh{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kmeshes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
