apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: notifier
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: event-display
          image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display

---

kind: Service
apiVersion: v1
metadata:
  name: notifier
  namespace: dev
spec:
  selector:
    app: notifier
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: notifier-trigger
  namespace: dev
  annotations:
    knative-eventing-injection: enabled
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: notifier
